### PR TITLE
fixed modman

### PR DESCRIPTION
**Pull request by pquerner**
modman throwing
  [ErrorException]
  Invalid row on line 1 has 1 parts, expected 2

### CODE REVIEW

**Comment by LeeSaferite** [comment]
You must be using an ancient version of modman or the hackathon installer?

**Comment by LeeSaferite** [comment]
modman has supported this syntax for a very long time and the hackathon installer fixed the bug in their code with release 3.0.3

https://github.com/Cotya/magento-composer-installer/commit/0fd53f29cc1a3a195604286f0d009e471c63add4

Is there a compelling reason to modify the modman file vs. changing the hackathon installer version requirement?

**Comment by pquerner** [comment]
We're on c89683ac8e8a925abb8658bbf164f95b3ec4ad56 which results in 2.x. Maybe some module we're running has it hardcoded somewhere, cant tell as of now.

Would be a shame to have people excluded running an older composer version than 3.x, no?

**Comment by pquerner** [comment]
composer.lock reveals that each statement of the hackathon-composer app wants version "*" installed.
Sometimes theres a "php>=5.4" or "php>=5.3". Could be that, or anything else.

How would I force the app do use the latest 3.x version, if my main composer.json also requires version "*".

//Edit
composer.json of 3.x version of the hackathon-composer reveals that it requires atleast php 5.4. Thats why we're on 2.x branch. :( Too bad..

**Comment by LeeSaferite** [comment]
Interesting. This module also has a requirement of PHP >= 5.4 as well. How are you able to install this module if you are running 5.3?

In any case, I will merge this even though I disagree with it just so people running the broken composer installer will not be left out.

**Pull request merged**
